name: Gif Comment
on:
  issues:
    types: [opened]
    
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add Gif comment
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.kbRES3zM4d5SgPSbpRBTrVCRpSaLcSDJ }}
          comment_type: 'gif'
